### PR TITLE
Run cargo fmt and fix documentation tests

### PR DESCRIPTION
**Pull request by JCapucho**

### CODE REVIEW

**Comment by haighcam** [comment]
I disagree with how cargo fmt handles some of the chains.
If you are going to format it please use chain_width = 100.

**Comment by JCapucho** [comment]
I can remove the formatting changes and just keep the documentation fixes if you want

**Comment by haighcam** [comment]
Sure that works for me. 
Though I would probably still end up running cargo fmt myself since I like most of the formatting it does (just not how it handles chains by default).

**Comment by haighcam** [comment]
I added a rustfmt.toml with the settings I would like for cargo fmt, so if you pull that and rerun cargo fmt then it should be good to merge.

**Comment by JCapucho** [comment]
I've rebase and reran cargo fmt, let me know if it's good now.

**Comment by haighcam** [comment]
Thanks, looks good.

**Pull request merged**
